{
    "parameter-id-u": 131,
    "parameter-id-v": 132,

    "legendre-loader": "mapped-memory",
    "matrix-loader": "file-io",

    "mir-cache-path": "/tmp/cache",

    "post-process": [
        "accuracy",
        "bitmap",
        "checkerboard",
        "griddef",
        "points",
        "edition",
        "formula",
        "frame",
        "packing",
        "pattern",
        "vod2uv",
        "compatibility"
    ]
}
