{
    "parameter-id-u": 131,
    "parameter-id-v": 132,

    "parameter-configuration": "~mir/etc/mir/parameter.yaml",

    "legendre-loader": "mapped-memory",
    "interpolator-loader": "file-io",

    "mir-cache-path": "/tmp/cache"
}
