{
    "legendre-loader": "mapped-memory",
    "matrix-loader": "file-io",

    "mir-cache-path": "/tmp/cache",

    "post-process": [
        "accuracy",
        "bitmap",
        "checkerboard",
        "compatibility",
        "edition",
        "format",
        "formula",
        "frame",
        "griddef",
        "latitudes",
        "longitudes",
        "packing",
        "pattern",
        "vod2uv"
    ]
}
