name: ci

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request
  pull_request: ~

  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  # Calls a reusable CI workflow to build & test the current repository.
  downstream-ci:
    name: downstream-ci
    uses: ecmwf-actions/private-downstream-ci/.github/workflows/downstream-ci.yml@main
    with:
      mir: ecmwf/mir@${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

  # ci-hpc:
  #   name: ci-hpc
  #   if: github.event_name == "pull_request"
  #   uses: ./.github/workflows/reusable-ci-hpc.yml
  #   with:
  #     mir: ecmwf/mir@${{ github.event.pull_request.head.sha }}
  #   secrets: inherit
