name: reusable-ci

on:
  workflow_call:
    inputs:
      eccodes:
        required: false
        type: string
      eckit:
        required: false
        type: string
      atlas:
        required: false
        type: string
      mir:
        required: false
        type: string

jobs:
  ci:
    name: ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v2
    with:
      repository: ${{ inputs.mir || 'ecmwf/mir@develop' }}
      name_prefix: mir-
      build_package_inputs: |
        repository: ${{ inputs.mir || 'ecmwf/mir@develop' }}
        dependencies: |
            ecmwf/ecbuild
            MathisRosenhauer/libaec@master
            ${{ inputs.eccodes || 'ecmwf/eccodes' }}
            ${{ inputs.eckit || 'ecmwf/eckit' }}
            ${{ inputs.atlas || 'ecmwf/atlas' }}
        dependency_branch: develop
        parallelism_factor: 8
    secrets: inherit
