name: reusable-ci-hpc

on:
  workflow_call:
    inputs:
      mir:
        required: false
        type: string
      eccodes:
        required: false
        type: string
      eckit:
        required: false
        type: string
      metkit:
        required: false
        type: string
      atlas:
        required: false
        type: string

jobs:
  ci-hpc:
    name: ci-hpc
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-hpc.yml@v2
    with:
      name-prefix: mir-
      build-inputs: |
        --package: ${{ inputs.mir || 'ecmwf/mir@develop' }}
        --modules: |
          ecbuild
          ninja
        --dependencies: |
          ${{ inputs.eccodes || 'ecmwf/eccodes@develop' }}
          ${{ inputs.eckit || 'ecmwf/eckit@develop' }}
          ${{ inputs.metkit || 'ecmwf/metkit@develop' }}
          ${{ inputs.atlas || 'ecmwf/atlas@develop' }}
        --parallel: 64
    secrets: inherit